import { property } from "@/lib/property";
const faqs=[
["Do I still own the PBRS land?","Yes. The PBRS acreage remains privately owned as part of the estate."],
["How can the forest be used?","The land can support walking and hiking trails and compatible recreational use such as dirt bikes, quads and side-by-sides. Existing trails may be enjoyed and additional trails may be created, subject to applicable requirements."],
["Can a portion be removed from PBRS?","King County provides a process for changes or removal. A future owner should confirm the procedure, timing and cost directly with the county before planning improvements."],
["What is the estimated removal cost?","The seller's current estimate is approximately $2,250 per acre. This is an estimate only and should be independently verified."],
["Why keep land in PBRS?","PBRS helps preserve the forest setting and can reduce the taxable value of enrolled acreage, supporting the privacy and natural character that define the property."],
];
export function PBRS(){return <section id="pbrs" className="section cream"><div className="container"><p className="eyebrow">Understanding PBRS</p><div className="split-heading"><h2>Protected forest. Lower taxes. Future flexibility.</h2><p>Approximately {property.pbrsAcres} acres are enrolled in King County's Public Benefit Rating System. The program helps retain the wooded setting while reducing the assessed value of enrolled land for property-tax purposes.</p></div><div className="pbrs-cards"><article><strong>{property.pbrsAcres}</strong><span>Approximate enrolled acres</span></article><article><strong>$2,250</strong><span>Estimated removal cost per acre</span></article><article><strong>Private</strong><span>Owned and enjoyed with the estate</span></article></div><div className="faq">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div><p className="disclaimer">PBRS descriptions and costs are provided for general marketing purposes and are not legal, tax or land-use advice. Buyers should independently verify permitted uses, tax treatment, removal costs, building feasibility and all county requirements.</p></div></section>}
