export const property = {
  name: "Enumclaw Forest Estate",
  tagline: "Modern Living. Immersed in Nature.",
  address: "23670 SE 448th St, Enumclaw, WA 98022",
  price: "$1,550,000",
  squareFeet: 3820,
  bedrooms: 4,
  bathrooms: 2.5,
  acres: 19.55,
  pbrsAcres: 17.5,
  yearBuilt: 2019,
  garageSqFt: 1000,
  coveredParking: 4,
  annualTaxes: 9618,
  taxYear: 2026,
  parcelNumber: "2220069212",
  schools: [
    { name: "Sunrise Elementary School", grades: "K–5", distance: "1.2 mi" },
    { name: "Enumclaw Middle School", grades: "6–8", distance: "1.3 mi" },
    { name: "Enumclaw Sr High School", grades: "9–12", distance: "1.2 mi" },
  ],
  realtor: {
    name: "Todd Huizenga",
    company: "KW Mountains to Sound Realty",
    phone: "253-569-5341",
    email: "toddh@kw.com",
    logoUrl: "/assets/logos/kw-mountains-to-sound.png",
  },
};

export const media = {
  hero: "/assets/photos/photo-63.jpeg",
  exterior: [
    "/assets/photos/photo-51.jpg",
    "/assets/photos/photo-52.jpg",
    "/assets/photos/photo-53.jpg",
    "/assets/photos/photo-54.jpg",
  ],
  trail: "/assets/photos/photo-61.jpg",
  aerial: "/assets/photos/photo-57.jpg",
  boundary: "/assets/photos/photo-64.jpg",
  location: "/assets/photos/photo-68.jpg",
  mountain: "/assets/photos/photo-67.jpg",
  floorplans: [
    { title: "Main Floor", url: "/assets/floorplans/main-floor.jpg" },
    { title: "Second Floor", url: "/assets/floorplans/second-floor.jpg" },
  ],
  interiors: [
    ["Great Room", "/assets/photos/photo-03.jpg"],
    ["Chef's Kitchen", "/assets/photos/photo-10.jpg"],
    ["Hidden Pantry", "/assets/photos/photo-19.jpg"],
    ["Commercial Dog Wash", "/assets/photos/photo-23.jpg"],
    ["Large Bonus Room", "/assets/photos/photo-24.jpg"],
    ["Primary Suite", "/assets/photos/photo-34.jpg"],
    ["Primary Bath", "/assets/photos/photo-38.jpg"],
    ["Covered Patio", "/assets/photos/photo-45.jpg"],
  ] as const,
  video: "https://listings.foto-guy.com/videos/019d3191-55d9-7303-8173-0973176473fd",
  matterport: "https://my.matterport.com/show/?m=JiT3r3aNSj1&nt=1&brand=0&mls=1&",
};
